# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24578444a68a2be8ad0e11eb8def9b7e223929b5052cfd9ff4920a14826eb965142a4016959301c7b91c5c112500d5c232edb186ea5b533e542d6b398ebb4289

test:
  secret_key_base: f5b987b4663a22818c40d9ad0e0fe1376c68f0fd5660ce62e3e4a2a85fe9c2f8d96b5e10f9182c6fdea5026a4e559b5a4d2f9205cee3d5d91afd6a9b4b00a7f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
